apiVersion: v1
kind: Secret
metadata:
  name: openai-api-secret
type: Opaque
data:
  OPENAI_API_KEY: Rk53VHppYXZVQWhNbVZWMUVaNlpVQVJQRzV1S2cwajQyYnlXTFRYVnE1YmViR3IxZGl5YkpRUUo5OUFMQUNmaE1rNVhKM3czQUFBQUFDT0dBb0FNDQo=
# Note: The value of OPENAI_API_KEY must be Base64-encoded.
# You can encode it using the following command:
# echo -n "your-actual-api-key" | base64

